name: gestion_produccion
description: Sistema de gesti贸n de producci贸n para fabricantes y clientes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  
  # Google Sign In
  google_sign_in: ^6.2.1
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.2.2
  # image_picker: ^1.2.1
  # firebase_storage: ^12.4.10
  country_picker: ^2.0.24
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Configuraci贸n del icono de la app
  assets:
    - assets/icon/
    - assets/

# Configuraci贸n de flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"